### PR TITLE
Prune unused l1 addr params

### PR DESCRIPTION
**Pull request by blozano-tt**
### Ticket
#110 

### Description
As of now, only three params are used within l1_address_params struct.
This PR removes the unused params from all locations.

### API Changes
This PR has API changes:
- [ ] https://github.com/tenstorrent/tt-metal/pull/14789

### CODE REVIEW

**Review by afuller-TT — APPROVED** [review]

**Review by pjanevskiTT — APPROVED** [review]
love the changes

**Comment by joelsmithTT** [comment]
Nice

**Comment by broskoTT** [comment]
According to #268 , please abide by the new rules of committing API breaking changes. Add this to your PR:

This PR has API changes:
- [ ] (If breaking change) tt_metal approved PR pointing to this branch: link
- [ ] (If breaking change) tt_debuda approved PR pointing to this branch: link

**Comment by blozano-tt** [comment]
> * [ ]  (If breaking change) tt_debuda approved PR pointing to this branch: link

What is tt_debuda? Link?

**Comment by pjanevskiTT** [comment]
https://github.com/tenstorrent/tt-debuda @tt-vjovanovic for write access if you don't have it

**Pull request merged**
