### PR TITLE
Updated the x86 version of create-ethernet-map to support BH

### PR DESCRIPTION
**Pull request by TTDRosen**
Looks like create-ethernet-map wasn't updated to support BH. This update doesn't include the aarch64 version because I don't have a real aarch64 linux system to test on.

### CODE REVIEW

**Review by joelsmithTT — APPROVED** [review]
How are these generated?  `cargo build --release` in Luwen?  Or something else?

**Comment by TTDRosen** [comment]
Yeah, specifically `cargo build --release --bin luwen-cem`

**Comment by blozano-tt** [comment]
I think if you rebase, precommit problem will go away

**Comment by broskoTT** [comment]
Wanted to update this PR, but I don't have permission in TTDRosen repo :) I can follow up this PR with the removal of blackhole_1chip_cluster.yaml and changing tests accordingly...

**Review by broskoTT — APPROVED** [review]

**Comment by pjanevskiTT** [comment]
@TTDRosen @joelsmithTT @broskoTT can we merge this, seems everything is fine. I need it for some changes, so I can change something here if needed before we merge it

**Pull request merged**
