### PR TITLE
Move atu disable to silicondevice destructor

### PR DESCRIPTION
**Pull request by broskoTT**
When I initially implemented ATU in https://github.com/tenstorrent/tt-umd/pull/13, I had the wrong impression that only a single TTDevice is allowed to be open. TTDevice are being opened multiple times when ran from Pybuda, furthermore tt_SiliconDevice can be opened multiple times.
I've now moved at which exact point is ATU disabled, to better reflect when it was even set up. 

This was tested with benchmark models on Pybuda.

This is a general fix for umd though, not Buda specific.

Buda still builds on main, hence the PR on main branch.

### CODE REVIEW

**Comment by abhullar-tt** [comment]
I know this PR was merged but do you think you can also push it to `metal-main`?

**Comment by broskoTT** [comment]
> I know this PR was merged but do you think you can also push it to `metal-main`?

I can cherry pick the commit on that branch.
But isn't the idea to merge the metal-main into main anyway?

**Comment by abhullar-tt** [comment]
> > I know this PR was merged but do you think you can also push it to `metal-main`?
> 
> I can cherry pick the commit on that branch. But isn't the idea to merge the metal-main into main anyway?

yeah I believe so, Im just not sure when this would happen

**Comment by pjanevskiTT** [comment]
Maybe it is a good moment to make a specific BBE branch, and we can review metal-main branch if that is going to speed up the process. So we can make changes on BBE branch if those changes are Buda specific. If not, we will merge it to main in a standard way

**Pull request merged**
